name: Greetings-New-Contributor

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.event.comment.user.login }}
        issue-message: |
          👋 Hello! @$USERNAME Welcome to the Kubestellar. 

          We're excited to have you here! Please make sure to check out our [contribution guide](./CONTRIBUTING.md) and feel free to join our [Slack channel](https://slack.example.com) for any questions.
        pr-message: 'Message that will be displayed on users first pr'
